### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by thewh1teagle** [dermasmid/get-chromedriver#1]
Make this package works with selenium
You can create function which will check if chromedriver already exist
if it does  - 
the function will skip the download 
if not
the function will download the driver
eventually the function will return the instance of selenium webdriver

What's cool about that is you will never carry again about webdriver because it will handle it for you

**Comment by dermasmid** [comment]
Checkout [this library](https://github.com/zaironjacobs/get-chrome-driver) for a more complete solution.
When i made this i did not see the library mentioned above.
What i made is more compact, and works only for Linux.
